### PR TITLE
setup-dev-sysrepo: various fixes

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by jpetrina** [comment]
LGTM, although I am not sure whether the library destination fix is required for everyone. Can you confirm @jsmolic and @jvijtiuk?

**Comment by jsmolic** [comment]
> LGTM, although I am not sure whether the library destination fix is required for everyone. Can you confirm @jsmolic and @jvijtiuk?

That's regarding the pcre part of the script I suppose. I see no harm in it so we can leave it...

**Comment by jpetrina** [comment]
@jsmolic Agreed, I'll go ahead and merge this. Thanks!

**Comment by jsmolic** [comment]
Thanks

**Pull request merged**
